---
- name: Wget Snapshot
  hosts: all
  become: true
  become_user: solv

  tasks:
    - name: Wget Snapshot
      shell: |
        cd /mnt/snapshot
        wget -c --trust-server-names {{ snapshot_url }}/snapshot.tar.bz2
        wget -c --trust-server-names {{ snapshot_url }}/incremental-snapshot.tar.bz2 
      args:
        chdir: /mnt/snapshot
        executable: /bin/bash
      async: 3600
      poll: 10
      failed_when: false
      when: snapshot_url is defined
