---
- name: Wget Snapshot
  hosts: all
  become: true
  become_user: solv

  tasks:
    - name: Wget Snapshot
      shell: |
        wget --trust-server-names  https://snapshots.avorio.network/mainnet-beta/snapshot.tar.bz2 https://snapshots.avorio.network/mainnet-beta/incremental-snapshot.tar.bz2
      args:
        chdir: /mnt/snapshot
        executable: /bin/bash
      async: 3600
      poll: 10
      failed_when: false