---
- name: Set Authoried Key to Identity
  hosts: all
  become: true
  become_user: solv
  vars:
    key_name: "{{ hostvars[inventory_hostname].identity_account }}.json"
    local_key_path: "~/.slv/keys/{{ key_name }}"
  tasks:
    - name: Set validator type fact for each host
      set_fact:
        validator_type: "{{ validator_type | default('firedancer') }}"

    - name: Debug validator type. Stop if not set
      debug:
        msg: "Validator type is {{ validator_type }}"

    - name: Fail if validator type is not set
      fail:
        msg: "Validator type is not set. Please set it in the inventory."
      when: validator_type is not defined

    - name: Read local validator key file securely (base64)
      become: false
      delegate_to: localhost
      slurp:
        src: "{{ local_key_path }}"
      register: key_file

    - name: Stop if key file not found
      fail:
        msg: "Key file not found: {{ local_key_path }}"
      when: key_file is not defined

    - name: Set Identity to Validator Key via stdin
      shell: . ~/.profile && agave-validator -l /mnt/ledger set-identity
      args:
        stdin: "{{ key_file.content | b64decode }}"
        executable: /bin/bash
      register: set_identity_result
      timeout: 20
      when: validator_type == 'jito'

    - name: Set Identity to Active Validator Key
      shell: |
        . ~/.profile
        sudo fdctl set-identity --config /home/solv/firedancer-config.toml /home/solv/mainnet-validator-keypair.json
      args:
        executable: /bin/bash
      when: validator_type == 'firedancer'

    - name: Add Authorized Voter via stdin
      shell: . ~/.profile && agave-validator -l /mnt/ledger authorized-voter add
      args:
        stdin: "{{ key_file.content | b64decode }}"
        executable: /bin/bash
      ignore_errors: yes
      when: validator_type == 'jito'

    - name: Add Authorized Voter
      shell: . ~/.profile && agave-validator -l /mnt/ledger authorized-voter add /home/solv/mainnet-validator-keypair.json
      args:
        executable: /bin/bash
      ignore_errors: yes
      when: validator_type == 'firedancer'
