---
- name: Install Prometheus on Ubuntu
  hosts: all
  become: yes
  vars:
    prometheus_version: "3.2.1"
    prometheus_file: "prometheus-{{ prometheus_version }}.linux-amd64"
    prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_file }}.tar.gz"
    prometheus_yml: "~/.slv/cmn/prometheus.yml"

  tasks:
    - name: Ensure solv user exists
      user:
        name: solv
        state: present
        create_home: yes
        shell: /bin/bash

    - name: debug
      debug:
        msg: "prometheus_yml: {{ prometheus_yml }}"

    - name: Download Prometheus tarball
      become_user: solv
      get_url:
        url: "{{ prometheus_url }}"
        dest: "/home/solv/{{ prometheus_file }}.tar.gz"
        mode: "0644"

    - name: Unarchive Prometheus tarball
      become_user: solv
      unarchive:
        src: "/home/solv/{{ prometheus_file }}.tar.gz"
        dest: "/home/solv/"
        remote_src: yes

    - name: Copy Prometheus binaries to /usr/local/bin
      copy:
        src: "/home/solv/{{ prometheus_file }}/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: solv
        group: solv
        mode: "0755"
        remote_src: yes
      with_items:
        - "prometheus"
        - "promtool"
      notify:
        - restart-prometheus

    - name: Create /etc/prometheus directory
      file:
        path: /etc/prometheus
        state: directory
        owner: solv
        group: solv
        mode: "0755"

    - name: Upload prometheus.yml from local templates directory (overwrite default)
      copy:
        src: "{{ prometheus_yml }}"
        dest: /etc/prometheus/prometheus.yml
        owner: solv
        group: solv
        mode: "0644"
      notify:
        - reload-prometheus # ここを reload に変更 (ノーダウンタイムで設定反映)

    - name: Create /var/lib/prometheus directory
      file:
        path: /var/lib/prometheus
        state: directory
        owner: solv
        group: solv
        mode: "0755"

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        mode: "0644"
        content: |
          [Unit]
          Description=Prometheus
          After=network-online.target
          Wants=network-online.target

          [Service]
          User=solv
          Group=solv
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus \
            --web.enable-lifecycle \
            --web.listen-address=0.0.0.0:3090
          ExecReload=/bin/kill -HUP $MAINPID
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      notify:
        - daemon-reload
        - restart-prometheus

    - name: Enable Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started

  handlers:
    - name: daemon-reload
      systemd:
        daemon_reload: yes

    - name: restart-prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes

    - name: reload-prometheus
      systemd:
        name: prometheus
        state: reloaded # ノーダウンタイムで設定反映
