---
- name: Install minimum required packages
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: setup_lib

    - name: Install development tools and libraries
      apt:
        name:
          - wget
          - aria2
        state: present
      tags: setup_lib
      failed_when: false
