---
- name: Clone and build Yellowstone GRPC with specific tag
  hosts: all
  vars_files:
    - ~/.slv/versions.yml
  become: true
  vars:
    working_dir: "/home/solv"
    repo_url: "https://github.com/rpcpool/yellowstone-grpc.git"
  tasks:
    - name: Clone or update the Yellowstone GRPC repository with specific tag
      git:
        repo: "{{ repo_url }}"
        dest: "{{ working_dir }}/yellowstone-grpc"
        version: "{{ geyser_version }}"
        update: yes
      become_user: solv
      vars:
        geyser_version: "{{ testnet_rpcs.geyser_version }}"

    - name: Build the project using Cargo
      shell: |
        source ~/.profile
        cargo build -r
      args:
        chdir: "{{ working_dir }}/yellowstone-grpc"
        executable: /bin/bash
      become_user: solv

    - name: Format and run config-check with Cargo
      shell: |
        source ~/.profile
        cargo fmt && cargo run --bin config-check -- --config '/home/solv/geyser.json'
      args:
        chdir: "{{ working_dir }}/yellowstone-grpc"
        executable: /bin/bash
      become_user: solv
